// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-GfvlFUc9d1CupZ2K5_5za7IfjrWbeQ4',
    appId: '1:641814034599:web:408108b66353e7187e8382',
    messagingSenderId: '641814034599',
    projectId: 'cargo-510e2',
    authDomain: 'cargo-510e2.firebaseapp.com',
    storageBucket: 'cargo-510e2.appspot.com',
    measurementId: 'G-9E2LX9Y444',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO9RUBtBOi8jMN0WnzVijr2pSwLzEPskk',
    appId: '1:641814034599:android:c7bf5c017910705f7e8382',
    messagingSenderId: '641814034599',
    projectId: 'cargo-510e2',
    storageBucket: 'cargo-510e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAgYsmqnSIAdRE1G0OCvSEVP2db6ozdZI',
    appId: '1:641814034599:ios:74c9d8c6396cd8ae7e8382',
    messagingSenderId: '641814034599',
    projectId: 'cargo-510e2',
    storageBucket: 'cargo-510e2.appspot.com',
    iosClientId: '641814034599-agnrccuqpa9sk4p4s1j4cducu2f577q3.apps.googleusercontent.com',
    iosBundleId: 'n',
  );
}
